#!/usr/bin/env python
# -*- coding: utf8 -*-

import os
source = "https://raw.github.com/baijian/bootstrap.py/v1.0/bootstrap.py"
target = "%s/bootstrap.py" % os.path.dirname(os.path.abspath(__file__))
if not os.path.isfile(target):
    os.system("wget %s -O %s" % (source, target))


from bootstrap import bootstrap, ve
bootstrap(os.path.dirname(os.path.abspath(__file__)) + "/..")


ve("pip install Fabric==1.6")
ve("pip install fabtools==0.13")
ve("vagrant up")
